//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPZ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        public int id { get; set; }
        public Nullable<int> codigo { get; set; }
        public int proveedorId { get; set; }
        public Nullable<System.DateTime> fechaFacturacion { get; set; }
        public Nullable<System.DateTime> fechaVencimiento { get; set; }
        public string descripcion { get; set; }
        public string moneda { get; set; }
        public Nullable<decimal> subtotal { get; set; }
        public Nullable<double> igv { get; set; }
        public Nullable<decimal> total { get; set; }
        public string estado { get; set; }
    
        public virtual Proveedor Proveedor { get; set; }
    }
}
